### ISSUE TITLE
TranscriptClean.py samFile not found error

### ISSUE THREAD

**Issue by davejwright3** [mortazavilab/TranscriptClean#20]
Hi there, 

I'm having a little trouble running TranscriptClean. I have a set of sorted bam files I wanted to run through it prior to Talon. I converted each bam back to sam (e.g. samtools -h my_sorted.bam > my_sorted.sam) and submitted the following: 

TranscriptClean --sam /my/indir/my_sorted.sam --genome /my/reference/my_genome.fa --outprefix /my/outdir/my_prefix

All dependancies are installed and seemingly run fine. The error received suggests there is an issue in reading the sam file;

 File "/opt/software/TranscriptClean/TranscriptClean.py", line 1593, in <module>
    main()
  File "/opt/software/TranscriptClean/TranscriptClean.py", line 37, in main
    header, sam_chroms, sam_chunks = split_SAM(sam_file, n_threads)
  File "/opt/software/TranscriptClean/TranscriptClean.py", line 502, in split_SAM
    with open(samFile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

I've had a look through the TranscriptClean.py source code and my sam files but can't find what may be causing the conflict. The sam files possess headers and seem to work fine with other analyses and the paths are correct in the submission script. Is this something you've maybe seen before? I must have made a mistake somewhere. Hopefully it's just a daft error, but I can't see it?

Many thanks for your time & insights,

Dave

**Comment by callumparr** [comment]
How did you solve this problem? I am having the same issue. This was only when submitting to our cluster but works fine interactively.
