### ISSUE TITLE
Cannot run TranscriptClean with qsub

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TranscriptClean#24]
I can run it beautifully interactively on our server but through qsub it gives this error. It is some issue with handling multi-threading? 

My base environment uses python 3.6.7 not 3.7 but it does work interactively so I assumed this shouldn't be the cause of issue.

#!/usr/bin

```
# Set source of conda install
source miniconda3/etc/profile.d/conda.sh
python TranscriptClean/TranscriptClean.py -t 4 --sam /analysisdata/rawseq/fastq/SHARED/000078/Mouse_aging/BAM_MD/Day1_01_DRS_pass.sam --genome /home/callum/Genome_files/Mus_muscu
/analysisdata/rawseq/fastq/SHARED/000078/Mouse_aging/TranscriptClean/scripts/TranscriptClean_Day1_01.sh
```

```
 (most recent call last):
  File "TranscriptClean/TranscriptClean.py", line 1593, in <module>
    main()
  File "TranscriptClean/TranscriptClean.py", line 37, in main
    header, sam_chroms, sam_chunks = split_SAM(sam_file, n_threads)
  File "TranscriptClean/TranscriptClean.py", line 513, in split_SAM
    chunks = split_input(transcript_lines, n)
  File "TranscriptClean/TranscriptClean.py", line 527, in split_input
    batch = my_list[index:]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by mei-du** [comment]
Following this issue. I am also getting this error when using a sorted or unsorted sam, although I've had a successful run in the past with a sorted subsample of the same data. I used -t 8 in all runs

**Comment by mei-du** [comment]
Hey @callumparr, I manually added int() to index of the function below in TranscriptClean.py and so far it's running well :)
```
def split_input(my_list, n):
    """ Splits input into n sublists of roughly equal size"""

    chunks = []
    index = 0
    batch_size = ceil(len(my_list)/n)
    while index < len(my_list):
        try:
            batch = my_list[int(index):int(index) + batch_size]
        except:
            batch = my_list[int(index):]
        chunks.append(batch)
        index += batch_size
```

**Comment by callumparr** [comment]
Ah cool, I will try this. I ended up running this interactively for all my samples but good to know.

**Comment by callumparr** [comment]
its works! Thanks. 

Is this a specific change required for python 3.6.7 rather than using pythong 3.7? 

I still not sure why I could use it interactively but need to change this for qsub job.
