### ISSUE TITLE
scalar errors in output but runs to completion 

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TranscriptClean#31]
I seem to have many errors but TranscriptClean just finish and joins up outputs into one file as expected.

Can these errors be ignored? 

I provide an example output file. 

**minimap2**

```
minimap2 -t 10 -2 -ax splice -uf --MD --junc-bed /home/scratch/callum/Genome_files/gencode.v39.annotation.bed --secondary=no /home/scratch/callum/Genome_files/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.mmi tail_trimmer/iPSC_rep1_run1_out/fastq/iPSC_rep1_run1_out.cleaned.fq.gz > iPSC_rep1_run1_pass_genome.sam
```

**TranscriptClean**

*python 3.6.5*

*commit ae9e71556a6b2e2c1fd80a9dca8fbab8d8196206 (HEAD -> master, tag: v2.0.3, origin/master, origin/HEAD)
Author: M. Hasan Celk <celikm@in.tum.de>
Date:   Fri Sep 3 19:04:55 2021 -0700*

```
python /home/callum/TranscriptClean/TranscriptClean.py -t 12 --sam iPSC_rep1_run1/iPSC_rep1_run1_pass_genome.sam --genome /home/scratch/callum/Genome_files/GRCh38_no_alt_analysis_set_GCA_000001405.15_cleanheader.fasta -j /home/scratch/callum/Genome_files/gencode.v39.annotation.SJs.txt --outprefix iPSC_rep1_run1/TranscriptClean_ver3 --deleteTmp --tmpDir iPSC_rep1_run1/TranscriptClean_ver3/tmp
```

[slurm-5134.out.txt](https://github.com/mortazavilab/TranscriptClean/files/8751502/slurm-5134.out.txt)

**Comment by fairliereese** [comment]
Hey! Sorry for the late response, but the latest commits have fixed this issue.
