### ISSUE TITLE
ImportError: cannot import name 'Fasta' from 'fasta'

### ISSUE THREAD

**Issue by Kapilavasthi6** [mortazavilab/TranscriptClean#35]
HI @nargesr,
Can you help to solve this issue with TranscriptClean
ImportError: cannot import name 'Fasta' from 'fasta'

**Comment by nargesr** [comment]
Hi,
it seems you don't have "pyfaidx" package!

Can you try installing "pyfaidx" package? 
you either use conda or pip to install it

**Comment by Kapilavasthi6** [comment]
Thank you @nargesr,
I have already installed "pyfaidx" using pip, still same error.

**Comment by nargesr** [comment]
can you try importing pyfaidx package and see if you can use Fasta function directly?

**Comment by nargesr** [comment]
Did you try importing pyfaidx package to see if you can use Fasta function directly?

you can look at their GitHub page to see how you can run it! it should be something like that

>>> from pyfaidx import Fasta
>>> genes = Fasta('tests/data/genes.fasta')

also try to clean your conda environment and reinstall everything

**Comment by nargesr** [comment]
@Kapilavasthi6 
oh I just noticed you didn't have the latest version of TranscriptClean
pull the latest version

**Comment by PT806** [comment]
> Hi @nargesr I have changed script in line 19 (from pyfasta import Fasta) to (from pyfaidx import Fasta)
> 
> now to its working, Thanks

That works for my error, too. Thanks very much.
