### ISSUE TITLE
Library suggestion 

### ISSUE THREAD

**Issue by giovanniquinones** [mortazavilab/TranscriptClean#37]
I noticed from the source code, that the library PyFasta is used to fetch genomic sequences. 
Using PyFaidx may be a better choice for this. Pyfaidx never loads the sequence to memory but instead makes use of the fasta index (.fai) to quickly fetch the sequences. This would significantly alleviate the memory requirements. 
I have a version of TranscriptClean with this library and based on a few tests, the output is unchanged while reducing virtual memory to less than half.

**Comment by fairliereese** [comment]
Thank you! The migration to pyfaidx should now be complete.
